name: Check for large files

on: [push, pull_request]

jobs:
  check-large-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find large files
        run: |
          git ls-files | xargs -I{} du -k {} | sort -nr | head -n 10
          git ls-files | xargs -I{} du -k {} | awk '$1 > 100000' && exit 1 || exit 0
